spring:
  application:
    name: ddlwlrma-ai-agent
    datasource:
      url: jdbc:postgresql://IP:5432/agentdb
      username: postgres
      password: xxxxxx
  ai:
    dashscope:
      api-key: xxxxxx
      chat:
        options:
          model: qwen-plus
    openai:
      api-key: xxxxxx
      base-url: xxxxxx
      chat:
        options:
          api-key: xxxxxx
          base-url: https://api-inference.modelscope.cn
          model: Qwen/Qwen2.5-72B-Instruct
          stream: false
      embedding:
        api-key: xxxxxx
        base-url: https://api.siliconflow.cn
        options:
          model: BAAI/bge-large-zh-v1.5
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
        #        sse:
        #          connections:
        #            server1:
        #              url: http://localhost:8127

  #    vectorstore:
  #      pgvector:
  #        index-type: HNSW
  #        dimensions: 1024
  #        distance-type: COSINE_DISTANCE
  #        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context_path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ddlwlrma.ddlwlrmaaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
search-api:
  api-key: xxxxxx
mail:
  username: "你的163邮箱@163.com"
  auth-code: "你的授权码"